version: '3.8'

services:
  frontend:
    build:
      context: ./loan-calculator-next
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_API_URL: 'https://pmovescalcapi.cataclysmstudios.net'
    depends_on:
      - backend
    networks:
      - loan-calculator-network

  backend:
    build:
      context: ./loan-calculator-backend
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    environment:
      ALLOWED_ORIGINS: 'https://pmovescalc.cataclysmstudios.net,http://localhost:3000,http://127.0.0.1:3000'
      PRODUCTION_DOMAIN: 'pmovescalc.cataclysmstudios.net'
    networks:
      - loan-calculator-network

networks:
  loan-calculator-network:
    driver: bridge