version: '3.8'

services:
  frontend:
    build:
      context: ./loan-calculator-next
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    build:
      context: ./loan-calculator-backend
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    environment:
      ALLOWED_ORIGINS: 'https://pmovescalc.cataclysmstudios.net'