version: '3.8'

services:
  frontend:
    build:
      context: ./loan-calculator-next
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000

  backend:
    build:
      context: ./loan-calculator-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"