version: '3.8'

services:
  frontend:
    build:
      context: ./loan-calculator-next
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:9000  # Use localhost for external access
    depends_on:
      - backend
    networks:
      - loan-calculator-network

  backend:
    build:
      context: ./loan-calculator-backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - PRODUCTION_DOMAIN=${PRODUCTION_DOMAIN:-your-production-domain.com}
    
    networks:
      - loan-calculator-network

networks:
  loan-calculator-network:
    driver: bridge